[server]
maxUploadSize = 50
maxMessageSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3498db"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
